# Generated by Django 3.2.5 on 2021-11-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_email_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('host_video', models.BooleanField(default=False, null=True)),
                ('participants_video', models.BooleanField(default=False, null=True)),
                ('participants_allow_time', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
            },
        ),
    ]
