# Generated by Django 3.2.5 on 2021-11-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='participants_allow_time',
            new_name='participants_join',
        ),
    ]
