# Generated by Django 3.2.5 on 2021-11-30 03:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211129_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
