# Generated by Django 3.2.5 on 2021-11-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_meeting_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
