# Generated by Django 3.2.5 on 2021-11-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_meeting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(blank=True, choices=[('End', 'End'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Continue', 'Continue'), ('Extend', 'Extend')], default='Pending', max_length=100, null=True),
        ),
    ]
